services:
  postgres:
    image: postgres:15
    container_name: postgres-hackaton
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecret123
      POSTGRES_DB: hackaton_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: